language: node_js
node_js:
  - '12'
  - '10'
  - '8'

cache: yarn

jobs:
  include:
    - stage: build
      script:
        - echo "Building package"
        - yarn install
        # - yarn test
        - yarn build
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_USERNAME
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          branch: master
